config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'words#index'
  resources :translations
  resources :languages
  resources :words

  namespace :api do
    namespace :v1 do
      resources :translations, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/language.rb
class Language < ApplicationRecord
  mount_uploader :flag, FlagUploader
  has_many :translations, dependent: :destroy
  has_many :words, through: :translations
end

app/models/translation.rb
class Translation < ApplicationRecord
  scope :from_unsplash, -> { includes(:word).where('words.image LIKE ?', '%unsplash.com%').references(:words) }
  scope :for_language, -> (lang) { includes(:language).where(languages: { language_code: lang }) }
  scope :for_grouping, -> (group) { includes(:word).where(words: { grouping: group }) if group }
  belongs_to :word
  belongs_to :language
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/word.rb
class Word < ApplicationRecord
  include PgSearch
  pg_search_scope :search_by_word, :against => [:word, :grouping],  using: {
    tsearch: {
      prefix: true
    }
  }
  
  scope :not_unsplash, -> { where.not('image LIKE ?', '%unsplash%') }
  
  has_many :translations, inverse_of: :word, dependent: :destroy
  has_many :languages, through: :translations
  
  accepts_nested_attributes_for :translations, reject_if: :all_blank, allow_destroy: true
  before_save :set_word_image, :downcase_grouping
  after_destroy :delete_photo
  
  # mount uploader must come AFTER before_save callback
  mount_uploader :photo, PhotoUploader
  
  paginates_per 10

  def delete_photo
    remove_photo!
  end

  def optimized_image
    photo.try(:optimized).try(:url)
  end

  def set_word_image
    use_image_link if self.image && self.image_changed?
  end

  def use_image_link
    self.remote_photo_url = self.image
  end

  def downcase_grouping
    self.grouping = self.grouping.try(:downcase)
  end
end

app/controllers/api/v1/translations_controller.rb
class Api::V1::TranslationsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    json_with translation_service.filtered_translations
  end

  private

  def translation_service_params
    @translation_service_params ||= TranslationServiceDecanter.decant(params)
  end

  def translation_service
    TranslationService.new(translation_service_params)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include RailsUtil::JsonHelper
  protect_from_forgery with: :exception
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  def index
    @languages = Language.all
  end

  def show
  end

  def new
    @language = Language.new
  end

  def edit
  end

  def create
    @language = Language.new(language_params)

    if @language.save
      redirect_to @language, notice: 'Language was successfully created.'
    else
      render :new
    end
  end

  def update
    if @language.update(language_params)
      redirect_to @language, notice: 'Language was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @language.destroy
    redirect_to languages_url, notice: 'Language was successfully destroyed.'
  end

  private
 
  def set_language
    @language = Language.find(params[:id])
  end

  def language_params
    params.require(:language).permit(:name, :language_key, :flag, :language_code)
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_translation, only: [:show, :edit, :update, :destroy]

  def index
    @translations = Translation.includes(:language, :word)
  end

  def show
  end

  def new
    @translation = Translation.new
  end

  def edit
  end

  def create
    @translation = Translation.new(translation_params)

    if @translation.save
      redirect_to @translation, notice: 'Translation was successfully created.'
    else
      render :new
    end
  end

  def update
    if @translation.update(translation_params)
      redirect_to @translation, notice: 'Translation was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @translation.destroy
    redirect_to translations_url, notice: 'Translation was successfully destroyed.'
  end

  private

  def set_translation
    @translation = Translation.find(params[:id])
  end

  def translation_params
    params.require(:translation).permit(:foreign_word, :foreign_pronunciation, :word_id, :language_id)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  def index
    @words = word_service.filtered_words
  end

  def show
  end

  def new
    @word = Word.new
  end

  def edit
  end

  def create
    @word = Word.new(word_params)

    if @word.save
      redirect_to @word, notice: 'Word was successfully created.'
    else
      render :new
    end
  end

  def update
    if @word.update(word_params)
      redirect_to @word, notice: 'Word was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @word.destroy
    redirect_to words_url, notice: 'Word was successfully destroyed.'
  end

  private

  def set_word
    @word = Word.find(params[:id])
  end

  def word_service
    @word_service ||= WordService.new(word_service_params)
  end

  def word_service_params
    @word_service_params ||= WordServiceDecanter.decant(params)
  end

  def word_params
    @word_params ||= WordDecanter.decant(params[:word])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/languages/_form.html.erb
<%= form_with(model: language, local: true) do |form| %>
  <% if language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :language_name %>
  </div>

  <div class="field">
    <%= form.label :language_key %>
    <%= form.text_field :language_key, id: :language_language_key %>
  </div>

  <div class="field">
    <%= form.label :language_code %>
    <%= form.text_field :language_code, id: :language_language_code %>
  </div>

  <div class="field">
    <%= form.label :flag %>
    <%= form.file_field :flag, id: :language_flag %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<h1>Languages</h1>

<div>
  <%= link_to 'New Language', new_language_path %>
</div>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Key</th>
      <th>Chrome TTS Key</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= language.name %></td>
        <td><%= language.language_key %></td>
        <td><%= language.language_code %></td>
        <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/languages/new.html.erb
<h1>New Language</h1>

<%= render 'form', language: @language %>
<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @language.name %>
</p>

<p>
  <strong>Language Key:</strong>
  <%= @language.language_key %>
</p>

<p>
  <strong>Chrome Text-to-Speech Language Key:</strong>
  <%= @language.language_code %>
</p>

<p>
  <strong>Flag Icon:</strong>
  <%= image_tag @language.flag.url %>
</p>

<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FotofluentAdmin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= link_to 'Words', words_path %></h1>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/translations/_form.html.erb
<%= form_with(model: translation, local: true) do |form| %>
  <% if translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :foreign_word %>
    <%= form.text_field :foreign_word, id: :translation_foreign_word %>
  </div>

  <div class="field">
    <%= form.label :word_id %>
    <%= form.text_field :word_id, id: :translation_word_id %>
  </div>

  <div class="field">
    <%= form.label :language_id %>
    <%= form.collection_select :language_id, Language.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/translations/edit.html.erb
<h1>Editing Translation</h1>

<%= render 'form', translation: @translation %>

<%= link_to 'Show', @translation %> |
<%= link_to 'Back', translations_path %>

app/views/translations/index.html.erb
<h1>Translations</h1>

<div>
  <%= link_to 'New Translation', new_translation_path %>
</div>
<br>

<table>
  <thead>
    <tr>
      <th>Language</th>
      <th>EN Word</th>
      <th>Foreign Word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @translations.each do |translation| %>
      <tr>
        <td><%= translation.language.name %></td>
        <td><%= translation.word.word %></td>
        <td><%= translation.foreign_word %></td>
        <td><%= link_to 'Show', translation %></td>
        <td><%= link_to 'Edit', edit_translation_path(translation) %></td>
        <td><%= link_to 'Destroy', translation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/translations/new.html.erb
<h1>New Translation</h1>

<%= render 'form', translation: @translation %>
<%= link_to 'Back', translations_path %>

app/views/translations/show.html.erb
<p>
  <strong>Language:</strong>
  <%= @translation.language.name %>
</p>

<p>
  <strong>Word:</strong>
  <%= @translation.word.word %>
</p>

<p>
  <strong>Foreign Word:</strong>
  <%= @translation.foreign_word %>
</p>

<p>
  <strong>Grouping:</strong>
  <%= @translation.word.grouping %>
</p>


<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :word %>
    <%= form.text_field :word, id: :word_word %>
  </div>

  <h4>Add an image link OR upload the image file (not both!)</h4>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image, id: :word_image %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo, id: :word_photo %>
  </div>

  <div class="field">
    <%= form.label :grouping %>
    <%= form.text_area :grouping, id: :word_grouping %>
  </div>

  <div class="field">
    <p><strong>Translations</strong></p>
    <%= form.fields_for :translations do |translation| %>
      <%= render 'translation_fields', f: translation %>
    <% end %>

    <div class="link">
      <%= link_to_add_association 'Add Translation', form, :translations %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/_translation_fields.html.erb
<div class="nested-fields">
  <div>
    <%= f.label :foreign_word %>
    <%= f.text_field :foreign_word %>

    <%= f.label :language_id %>
    <%= f.collection_select :language_id, Language.all, :id, :name %>
  </div>

  <br>

  <div>
    <%= f.check_box :_destroy %>
    <%= f.label 'Check To Delete Translation' %>
  </div>
  
  <br>
  
  <div>
    <%= link_to_remove_association "Cancel New Translation", f %>
  </div>

  <br>
</div>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<div>
  <h3>Search Words</h3>
  
  <div>
    <%= form_tag words_path, method: :get do %>
      <%= text_field_tag :search_term, params[:search_term], placeholder: "Search for word or grouping" %>
      <%= submit_tag 'Search!' %>
    <% end %>
  </div>

  <br>

  <div>
    <%= form_tag words_path, method: :get do %>
      <%= hidden_field_tag :photo_src, 'not_unsplash' %>
      <%= submit_tag 'Words with Non-Unsplash Images' %>
    <% end %>
  </div>
</div>

<br>

<div>
  <%= link_to 'New Word', new_word_path %>
</div>
<br>

<div>
  <%= paginate @words %>
</div>
<br>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Image</th>
      <th>Grouping</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= image_tag 'loading.gif', 'data-src': image_url(word.optimized_image), width: 100, class: "lazy-load" %></td>
        <td><%= word.grouping %></td>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @words %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>
<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<div>
  <%= link_to 'Add New Word', new_word_path %>
</div>
<br>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Image:</strong>
  <br>
  <%= image_tag @word.photo.url, width: 100 %>
</p>

<p>
  <strong>Image Link:</strong>
  <br>
  <%= @word.photo.url %>
</p>

<p>
  <strong>Grouping:</strong>
  <%= @word.grouping %>
</p>

<hr>

<p><strong>Translations</strong></p>

<table>
  <tr>
    <th>Language</th>
    <th>Word</th>
  </tr>
  <% @word.translations.includes(:language).each do |translation| %>
    <tr>
      <td><%= translation.language.name %></td>
      <td><%= translation.foreign_word %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>